#!/usr/bin/env Rscript

# Build the aligned fixed-O2 and fitted-landscape parameter summary.
# The historical script and intermediate-output basenames retain "historical panel".
#
# The shared parameter rows link:
#   1. signed single-parameter AUC across 201 fixed-O2 concentrations;
#   2. each parameter's peak discriminative AUC and the O2 at that peak;
#   3. cluster-wise prior-referenced parameter positions for exploratory groups
#      of the 500 separate in vivo fitted endpoints.
#
# A complete 18-parameter faceted violin plot is exported as a supplementary
# figure. The main combined panel uses median/IQR/5th-95th intervals because
# 54 full violins would make the manuscript panel unreadable.

suppressPackageStartupMessages({
  library(data.table)
  library(ggrepel)
  library(ggplot2)
  library(patchwork)
  library(scales)
})

script_path <- local({
  file_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (length(file_arg)) {
    normalizePath(sub("^--file=", "", file_arg[[1L]]), mustWork = FALSE)
  } else {
    normalizePath("parameter_landscape.R", mustWork = FALSE)
  }
})
script_dir <- dirname(script_path)
data_dir <- normalizePath(
  Sys.getenv("ANALYSIS_DATA_DIR", unset = file.path(script_dir, "data")),
  mustWork = TRUE
)
figure_dir <- normalizePath(
  Sys.getenv(
    "PLOT_OUTPUT_DIR",
    unset = file.path(script_dir, "figures")
  ),
  mustWork = FALSE
)
dir.create(data_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

auc_path <- file.path(data_dir, "parameter_auc_by_o2.tsv")
parameter_meta_path <- file.path(data_dir, "parameter_function_groups.tsv")
parameter_palette_path <- file.path(data_dir, "parameter_function_group_palette.tsv")
best_parameter_path <- file.path(data_dir, "invivo_best_parameters_500seeds.tsv")
cluster_path <- file.path(
  data_dir,
  "invivo_best_tsne_cluster_coordinates.tsv"
)
cluster_summary_path <- file.path(
  data_dir,
  "invivo_tsne_cluster_summary.tsv"
)
tsne_run_metadata_path <- file.path(data_dir, "invivo_tsne_run_metadata.tsv")
bound_path <- file.path(data_dir, "invivo_parameter_table_seed25.csv")

required_paths <- c(
  auc_path, parameter_meta_path, parameter_palette_path, best_parameter_path, cluster_path,
  cluster_summary_path, tsne_run_metadata_path, bound_path
)
missing_paths <- required_paths[!file.exists(required_paths)]
if (length(missing_paths)) {
  stop("Missing aligned parameter landscape input(s): ", paste(missing_paths, collapse = ", "))
}

auc <- fread(auc_path)
parameter_meta <- fread(parameter_meta_path)
parameter_palette_meta <- fread(parameter_palette_path)
best_parameters <- fread(best_parameter_path)
clusters_raw <- fread(cluster_path)[dataset == "invivo"]
cluster_summary <- fread(cluster_summary_path)[dataset == "invivo"]
tsne_run_metadata <- fread(tsne_run_metadata_path)
bounds <- fread(bound_path)
tsne_metric <- function(key_name) {
  value <- tsne_run_metadata[tsne_run_metadata$key == key_name, value]
  if (length(value) != 1L) {
    stop("Missing or duplicated in vivo t-SNE run metadata key: ", key_name)
  }
  as.character(value[[1L]])
}
if (tsne_metric("fit_scope") != "separate_in_vivo_only" ||
    as.integer(tsne_metric("retained_initial_rows")) != 127500L ||
    as.integer(tsne_metric("best_endpoint_rows")) != 500L ||
    as.integer(tsne_metric("total_tsne_rows")) != 128000L ||
    as.integer(tsne_metric("tsne_parameters")) != 18L ||
    tsne_metric("excluded_variables") != "rho_2N,sigma_burden") {
  stop("The t-SNE run metadata does not match the approved analysis contract.")
}

required_auc_columns <- c(
  "O2_pct", "parameter", "parameter_group", "raw_auc_ge_2_positive",
  "discriminative_auc", "signed_auc_for_color", "direction"
)
if (!all(required_auc_columns %in% names(auc))) {
  stop("AUC table is missing: ", paste(setdiff(required_auc_columns, names(auc)), collapse = ", "))
}
if (nrow(auc) != 18L * 201L ||
    uniqueN(auc$parameter) != 18L ||
    uniqueN(auc$O2_pct) != 201L) {
  stop("Aligned parameter landscape requires 18 parameters x 201 O2 values.")
}
if (nrow(parameter_meta) != 18L || !identical(parameter_meta$parameter_order, seq_len(18L))) {
  stop("Parameter metadata must contain the ordered 18-parameter parameter landscape set.")
}
if (nrow(parameter_palette_meta) != 5L ||
    !identical(parameter_palette_meta$group_order, seq_len(5L)) ||
    !setequal(parameter_meta$parameter_group, parameter_palette_meta$parameter_group)) {
  stop("Parameter-function palette must define the five ordered response groups.")
}

# The AUC table retains the historical parameter-group labels generated by the
# fixed-O2 workflow. Replace those labels with the current shared response
# taxonomy without changing any AUC values.
auc[, c("parameter_group") := NULL]
auc <- merge(
  auc,
  parameter_meta[, .(parameter, parameter_group, parameter_order)],
  by = "parameter",
  all.x = TRUE,
  sort = FALSE
)
setorder(auc, parameter_order, O2_pct)

clusters <- clusters_raw[, .(
  seed_number = as.integer(seed),
  tSNE1 = as.numeric(tSNE1),
  tSNE2 = as.numeric(tSNE2),
  cluster_id,
  cluster_num = as.integer(cluster_num),
  cluster_k = as.integer(cluster_k),
  cluster_silhouette_avg = as.numeric(cluster_silhouette_avg)
)]
if (nrow(best_parameters) != 500L || nrow(clusters) != 500L ||
    anyDuplicated(best_parameters$seed_number) || anyDuplicated(clusters$seed_number)) {
  stop("Aligned parameter landscape requires 500 unique fitted endpoints and cluster assignments.")
}

merged <- merge(best_parameters, clusters, by = "seed_number", all = FALSE)
setorder(merged, seed_number)
if (nrow(merged) != 500L || !identical(merged$seed_number, seq_len(500L))) {
  stop("Parameter/cluster join did not recover seed 1 through seed 500 exactly once.")
}

observed_sizes <- table(merged$cluster_id)
cluster_summary_sizes <- setNames(
  as.integer(cluster_summary$n_seeds),
  as.character(cluster_summary$cluster_id)
)
cluster_levels <- sprintf(
  "vi_C%02d",
  seq_len(length(cluster_summary_sizes))
)
cluster_summary_sizes <- cluster_summary_sizes[cluster_levels]
if (anyNA(cluster_summary_sizes) ||
    !identical(
      as.integer(observed_sizes[cluster_levels]),
      unname(cluster_summary_sizes)
    ) ||
    sum(cluster_summary_sizes) != 500L) {
  stop("Cluster assignments do not match the generated in vivo t-SNE summary.")
}
selected_k <- unique(merged$cluster_k)
selected_silhouette <- unique(merged$cluster_silhouette_avg)
if (length(selected_k) != 1L ||
    selected_k != length(cluster_levels) ||
    length(selected_silhouette) != 1L ||
    !is.finite(selected_silhouette)) {
  stop("The generated in vivo t-SNE cluster metadata is inconsistent.")
}

all_parameters <- parameter_meta$parameter
cluster_input_parameters <- all_parameters
projected_only_parameters <- setdiff(all_parameters, cluster_input_parameters)
if (length(projected_only_parameters)) {
  stop(
    "All 18 displayed parameters must be inputs to the in vivo-only t-SNE."
  )
}

bound_meta <- bounds[
  estimate == TRUE & param_prototype %in% all_parameters,
  .(
    parameter = param_prototype,
    optimizer_parameter = param_name,
    lower_bound = as.numeric(prototype_lower_bound),
    upper_bound = as.numeric(prototype_upper_bound),
    transformation = ifelse(grepl("^log10_", param_name), "log10", "identity")
  )
]
if (nrow(bound_meta) != 18L || !setequal(bound_meta$parameter, all_parameters)) {
  stop("Could not recover configured bounds for all 18 parameters.")
}

prior_sd <- sqrt(1 / 12)
parameter_long <- rbindlist(lapply(all_parameters, function(parameter_name) {
  meta <- bound_meta[parameter == parameter_name]
  values <- as.numeric(merged[[parameter_name]])
  lower_natural <- meta$lower_bound[[1L]]
  upper_natural <- meta$upper_bound[[1L]]
  if (identical(meta$transformation[[1L]], "log10")) {
    if (any(!is.finite(values) | values <= 0) ||
        lower_natural <= 0 || upper_natural <= 0) {
      stop("Non-positive log10 value for ", parameter_name)
    }
    transformed <- log10(values)
    lower_transformed <- log10(lower_natural)
    upper_transformed <- log10(upper_natural)
  } else {
    transformed <- values
    lower_transformed <- lower_natural
    upper_transformed <- upper_natural
  }
  prior_unit <- (transformed - lower_transformed) /
    (upper_transformed - lower_transformed)
  data.table(
    seed_number = merged$seed_number,
    cluster_id = merged$cluster_id,
    tSNE1 = merged$tSNE1,
    tSNE2 = merged$tSNE2,
    parameter = parameter_name,
    natural_value = values,
    transformed_value = transformed,
    prior_unit = prior_unit,
    prior_referenced_z = (prior_unit - 0.5) / prior_sd,
    transformation = meta$transformation[[1L]],
    lower_bound = lower_natural,
    upper_bound = upper_natural,
    cluster_role = ifelse(
      parameter_name %in% cluster_input_parameters,
      "Used in 18-parameter in vivo-only t-SNE construction",
      "Projected onto existing clusters only"
    )
  )
}))

parameter_long <- merge(
  parameter_long,
  parameter_meta[, .(
    parameter, parameter_group, parameter_description, parameter_order
  )],
  by = "parameter",
  all.x = TRUE,
  sort = FALSE
)
setorder(parameter_long, parameter_order, seed_number)
if (nrow(parameter_long) != 18L * 500L ||
    any(!is.finite(parameter_long$prior_referenced_z))) {
  stop("The 18-parameter prior-referenced table is incomplete or non-finite.")
}

cluster_intervals <- parameter_long[, .(
  n = .N,
  median_prior_z = median(prior_referenced_z),
  q05_prior_z = quantile(prior_referenced_z, 0.05),
  q25_prior_z = quantile(prior_referenced_z, 0.25),
  q75_prior_z = quantile(prior_referenced_z, 0.75),
  q95_prior_z = quantile(prior_referenced_z, 0.95),
  mean_prior_z = mean(prior_referenced_z),
  natural_median = median(natural_value),
  natural_q25 = quantile(natural_value, 0.25),
  natural_q75 = quantile(natural_value, 0.75)
), by = .(
  parameter, parameter_group, parameter_order, cluster_role, cluster_id
)]

cluster_difference <- parameter_long[, {
  grand_mean <- mean(prior_unit)
  total_ss <- sum((prior_unit - grand_mean)^2)
  between_ss <- sum(vapply(
    split(prior_unit, cluster_id),
    function(x) length(x) * (mean(x) - grand_mean)^2,
    numeric(1)
  ))
  .(
    eta_squared_cluster = if (total_ss > 0) between_ss / total_ss else NA_real_,
    max_pairwise_cluster_mean_difference = {
      means <- tapply(prior_referenced_z, cluster_id, mean)
      max(means) - min(means)
    }
  )
}, by = .(parameter, parameter_group, parameter_order, cluster_role)]
setorder(cluster_difference, -eta_squared_cluster, parameter_order)
cluster_difference[, rank_eta_squared := seq_len(.N)]

peak_auc <- auc[, {
  maximum <- max(discriminative_auc, na.rm = TRUE)
  candidates <- .SD[abs(discriminative_auc - maximum) < 1e-12]
  candidates <- candidates[order(O2_pct)]
  candidates[1L]
}, by = .(parameter, parameter_group, parameter_order)]
peak_auc[, peak_direction_class := fifelse(
  raw_auc_ge_2_positive > 0.5,
  "Higher values associated with dominant_mean_ploidy >= 2",
  "Higher values associated with dominant_mean_ploidy < 2"
)]

fwrite(
  parameter_long,
  file.path(data_dir, "cluster_parameter_values.tsv"),
  sep = "\t"
)
fwrite(
  cluster_intervals,
  file.path(data_dir, "cluster_prior_interval_summary.tsv"),
  sep = "\t"
)
fwrite(
  cluster_difference,
  file.path(data_dir, "cluster_difference_ranking.tsv"),
  sep = "\t"
)
fwrite(
  peak_auc,
  file.path(data_dir, "peak_auc_by_parameter.tsv"),
  sep = "\t"
)
fwrite(
  clusters,
  file.path(data_dir, "tsne_cluster_coordinates.tsv"),
  sep = "\t"
)

setorder(parameter_palette_meta, group_order)
group_levels <- parameter_palette_meta$parameter_group
group_palette <- setNames(
  parameter_palette_meta$color,
  parameter_palette_meta$parameter_group
)
available_cluster_palette <- c(
  "#2D2D2D", "#858585", "#C59B2A", "#486A8C",
  "#8A5A44", "#5E7D63", "#7B668C", "#A46776"
)
available_cluster_shapes <- c(21, 22, 24, 23, 25, 21, 22, 24)
if (length(cluster_levels) > length(available_cluster_palette)) {
  stop("No explicit plotting palette is defined for the selected cluster count.")
}
cluster_palette <- setNames(
  available_cluster_palette[seq_along(cluster_levels)],
  cluster_levels
)
cluster_shapes <- setNames(
  available_cluster_shapes[seq_along(cluster_levels)],
  cluster_levels
)
direction_palette <- c(
  "Higher values associated with dominant_mean_ploidy >= 2" = "#B2182B",
  "Higher values associated with dominant_mean_ploidy < 2" = "#2166AC"
)

tsne_full_boundary_path <- file.path(
  data_dir, "tsne_assignment_boundaries.tsv"
)

# One solid convex hull contains every endpoint assigned to each exploratory
# cluster. This is a descriptive membership range, not a confidence region.
tsne_full_boundaries <- clusters[, {
  hull_index <- chull(tSNE1, tSNE2)
  closed_hull_index <- c(hull_index, hull_index[[1L]])
  data.table(
    region_vertex_order = seq_along(closed_hull_index),
    tSNE1 = tSNE1[closed_hull_index],
    tSNE2 = tSNE2[closed_hull_index],
    n_cluster_total = .N,
    n_assignment_retained = .N,
    retained_fraction = 1,
    boundary_method = paste0(
      "Convex hull of all endpoints assigned to the exploratory ",
      "cluster in the t-SNE plane"
    )
  )
}, by = cluster_id]
setorder(tsne_full_boundaries, cluster_id, region_vertex_order)
fwrite(tsne_full_boundaries, tsne_full_boundary_path, sep = "\t")

parameter_axis <- copy(parameter_meta)
parameter_axis[, parameter_y := 19 - parameter_order]
parameter_axis[, cluster_role_mark := ifelse(
  parameter %in% cluster_input_parameters, "\u25cf", "\u25cb"
)]
parameter_axis[, parameter_axis_label := paste(parameter, cluster_role_mark)]

auc_plot_data <- merge(
  auc,
  parameter_axis[, .(
    parameter, parameter_y, parameter_axis_label, parameter_group
  )],
  by = c("parameter", "parameter_group"),
  all.x = TRUE,
  sort = FALSE
)
peak_plot_data <- merge(
  peak_auc,
  parameter_axis[, .(parameter, parameter_y)],
  by = "parameter",
  all.x = TRUE,
  sort = FALSE
)
interval_plot_data <- merge(
  cluster_intervals,
  parameter_axis[, .(parameter, parameter_y)],
  by = "parameter",
  all.x = TRUE,
  sort = FALSE
)
cluster_offsets <- setNames(
  seq(0.32, -0.32, length.out = length(cluster_levels)),
  cluster_levels
)
interval_plot_data[, plot_y := parameter_y + cluster_offsets[cluster_id]]

group_end_order <- parameter_meta[
  ,
  .(last_parameter_order = max(parameter_order)),
  by = parameter_group
][
  match(group_levels, parameter_group)
]
separator_y <- 18.5 - head(group_end_order$last_parameter_order, -1L)

function_group_blocks <- parameter_axis[
  ,
  .(
    ymin = min(parameter_y) - 0.5,
    ymax = max(parameter_y) + 0.5
  ),
  by = parameter_group
][
  match(group_levels, parameter_group)
]
function_group_annotation_layers <- lapply(
  seq_len(nrow(function_group_blocks)),
  function(i) {
    annotate(
      "rect",
      xmin = -0.20,
      xmax = -0.14,
      ymin = function_group_blocks$ymin[[i]],
      ymax = function_group_blocks$ymax[[i]],
      fill = unname(
        group_palette[[function_group_blocks$parameter_group[[i]]]]
      ),
      color = NA
    )
  }
)

p_heat <- ggplot(
  auc_plot_data,
  aes(x = O2_pct, y = parameter_y, fill = signed_auc_for_color)
) +
  geom_tile(width = 0.025, height = 0.88) +
  function_group_annotation_layers +
  geom_hline(
    yintercept = separator_y, linewidth = 0.45, color = "#505050"
  ) +
  scale_x_continuous(
    name = expression(paste("Fixed ", O[2], " concentration (%)")),
    limits = c(-0.22, 5.0125),
    breaks = seq(0, 5, by = 1),
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    name = NULL,
    breaks = parameter_axis$parameter_y,
    labels = parameter_axis$parameter_axis_label,
    limits = c(0.5, 18.5),
    expand = c(0, 0)
  ) +
  scale_color_manual(
    values = group_palette,
    breaks = names(group_palette),
    guide = "none"
  ) +
  scale_fill_gradientn(
    colors = c("#2166AC", "#F7F7F7", "#F7F7F7", "#F7F7F7", "#B2182B"),
    values = rescale(c(-1, -0.5, 0, 0.5, 1)),
    limits = c(-1, 1),
    breaks = c(-1, -0.75, 0, 0.75, 1),
    labels = c("1.00", "0.75", "0.50", "0.75", "1.00"),
    na.value = "#D9D9D9",
    oob = squish,
    guide = "none"
  ) +
  labs(title = "Oxygen-dependent outcome separation") +
  coord_cartesian(clip = "off") +
  theme_bw(base_size = 9.2, base_family = "Arial") +
  theme(
    plot.title = element_text(face = "bold", size = 14.5, margin = margin(b = 5)),
    axis.title.x = element_text(size = 14, margin = margin(t = 6)),
    axis.text.x = element_text(size = 11, color = "#202020"),
    axis.text.y = element_text(size = 15.5, color = "#202020"),
    axis.ticks.y = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_rect(color = "#707070", linewidth = 0.35),
    legend.position = "none",
    plot.margin = margin(4, 4, 4, 12)
  )

p_peak <- ggplot(
  peak_plot_data,
  aes(y = parameter_y, x = discriminative_auc)
) +
  geom_hline(
    yintercept = separator_y, linewidth = 0.45, color = "#505050"
  ) +
  geom_segment(
    aes(x = 0.5, xend = discriminative_auc, yend = parameter_y),
    linewidth = 0.65,
    color = "#A9ADB2"
  ) +
  geom_point(
    aes(fill = peak_direction_class),
    shape = 21, size = 2.4, stroke = 0.4, color = "#202020"
  ) +
  geom_text(
    aes(label = sprintf("%.2f", O2_pct)),
    nudge_x = 0.025, hjust = 0,
    size = 12 / ggplot2::.pt, color = "#333333"
  ) +
  scale_fill_manual(values = direction_palette, guide = "none") +
  scale_x_continuous(
    name = "Peak AUC",
    limits = c(0.5, 1.10),
    breaks = c(0.75, 1.0),
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    name = NULL, breaks = parameter_axis$parameter_y,
    labels = NULL, limits = c(0.5, 18.5), expand = c(0, 0)
  ) +
  labs(
    title = "Peak separation",
    subtitle = "Labels: O2 at peak"
  ) +
  coord_cartesian(clip = "off") +
  theme_bw(base_size = 8.8, base_family = "Arial") +
  theme(
    plot.title = element_text(face = "bold", size = 14.5, margin = margin(b = 1)),
    plot.subtitle = element_text(size = 10.8, color = "#555555", margin = margin(b = 5)),
    axis.title.x = element_text(size = 14, margin = margin(t = 6)),
    axis.text.x = element_text(size = 11),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color = "#E3E5E8", linewidth = 0.3),
    panel.border = element_rect(color = "#707070", linewidth = 0.35),
    plot.margin = margin(4, 10, 4, 4)
  )

p_prior <- ggplot(interval_plot_data, aes(y = plot_y)) +
  geom_hline(
    yintercept = setdiff(seq(1.5, 17.5, by = 1), separator_y),
    linewidth = 0.28, linetype = "22", color = "#C3C7CB"
  ) +
  geom_hline(
    yintercept = separator_y, linewidth = 0.45, color = "#505050"
  ) +
  geom_vline(xintercept = 0, linewidth = 0.45, color = "#575B60") +
  geom_segment(
    aes(
      x = q05_prior_z, xend = q95_prior_z,
      yend = plot_y, color = cluster_id
    ),
    linewidth = 0.45
  ) +
  geom_segment(
    aes(
      x = q25_prior_z, xend = q75_prior_z,
      yend = plot_y, color = cluster_id
    ),
    linewidth = 1.45
  ) +
  geom_point(
    aes(
      x = median_prior_z, fill = cluster_id,
      shape = cluster_id, color = cluster_id
    ),
    size = 2.25, stroke = 0.45
  ) +
  scale_color_manual(
    values = cluster_palette,
    guide = "none"
  ) +
  scale_fill_manual(
    values = cluster_palette,
    guide = "none"
  ) +
  scale_shape_manual(
    values = cluster_shapes,
    guide = "none"
  ) +
  scale_x_continuous(
    name = "Prior-referenced parameter position",
    limits = c(-1.78, 1.78),
    breaks = c(-1.5, 0, 1.5),
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    name = NULL, breaks = parameter_axis$parameter_y,
    labels = NULL, limits = c(0.5, 18.5), expand = c(0, 0)
  ) +
  labs(
    title = "Cluster-wise fitted-parameter positions",
    subtitle = "Point: median; thick: IQR; thin: 5th-95th percentile"
  ) +
  theme_bw(base_size = 8.8, base_family = "Arial") +
  theme(
    plot.title = element_text(face = "bold", size = 14.5, margin = margin(b = 1)),
    plot.subtitle = element_text(size = 10.8, color = "#555555", margin = margin(b = 5)),
    axis.title.x = element_text(size = 14, margin = margin(t = 6)),
    axis.text.x = element_text(size = 11),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color = "#E3E5E8", linewidth = 0.3),
    panel.border = element_rect(color = "#707070", linewidth = 0.35),
    legend.position = "none",
    plot.margin = margin(4, 4, 4, 4)
  )

tsne_centers <- clusters[, .(
  tSNE1 = median(tSNE1),
  tSNE2 = median(tSNE2),
  n = .N
), by = cluster_id]
tsne_x_range <- range(clusters$tSNE1, finite = TRUE)
tsne_y_range <- range(clusters$tSNE2, finite = TRUE)
tsne_span <- max(diff(tsne_x_range), diff(tsne_y_range)) * 1.06
tsne_x_mid <- mean(tsne_x_range)
tsne_y_mid <- mean(tsne_y_range)
tsne_x_limits <- tsne_x_mid + c(-0.5, 0.5) * tsne_span
tsne_y_limits <- tsne_y_mid + c(-0.5, 0.5) * tsne_span
tsne_x_breaks <- pretty(tsne_x_limits, n = 3)
tsne_y_breaks <- pretty(tsne_y_limits, n = 3)

# Start each label outside the densest part of its cluster. The nudge direction
# is derived from the cluster median relative to the full endpoint cloud, so it
# remains deterministic when the selected number of clusters changes.
tsne_global_center <- c(
  tSNE1 = median(clusters$tSNE1),
  tSNE2 = median(clusters$tSNE2)
)
tsne_visible_labels <- copy(tsne_centers)
tsne_visible_labels[, `:=`(
  direction_x = tSNE1 - tsne_global_center[["tSNE1"]],
  direction_y = tSNE2 - tsne_global_center[["tSNE2"]]
)]
tsne_visible_labels[, direction_norm := sqrt(direction_x^2 + direction_y^2)]
zero_direction <- !is.finite(tsne_visible_labels$direction_norm) |
  tsne_visible_labels$direction_norm < 1e-12
if (any(zero_direction)) {
  fallback_angles <- seq(
    0,
    2 * pi,
    length.out = sum(zero_direction) + 1L
  )[-(sum(zero_direction) + 1L)]
  tsne_visible_labels[zero_direction, `:=`(
    direction_x = cos(fallback_angles),
    direction_y = sin(fallback_angles),
    direction_norm = 1
  )]
}
tsne_visible_labels[, `:=`(
  nudge_x = direction_x / direction_norm * tsne_span * 0.10,
  nudge_y = direction_y / direction_norm * tsne_span * 0.10
)]
tsne_visible_labels[, label := sprintf(
  "%s\nn=%d", sub("^vi_", "", cluster_id), n
)]
tsne_repel_data <- rbind(
  clusters[, .(
    cluster_id, tSNE1, tSNE2, label = "",
    nudge_x = 0, nudge_y = 0
  )],
  tsne_visible_labels[, .(
    cluster_id, tSNE1, tSNE2, label, nudge_x, nudge_y
  )],
  use.names = TRUE
)

p_tsne <- ggplot(clusters, aes(x = tSNE1, y = tSNE2)) +
  geom_path(
    data = tsne_full_boundaries,
    aes(x = tSNE1, y = tSNE2, group = cluster_id, color = cluster_id),
    inherit.aes = FALSE,
    linewidth = 0.65, linetype = "solid", alpha = 0.82
  ) +
  geom_point(
    aes(fill = cluster_id, shape = cluster_id, color = cluster_id),
    size = 1.2, alpha = 0.58, stroke = 0.2
  ) +
  geom_label_repel(
    data = tsne_repel_data,
    aes(x = tSNE1, y = tSNE2, label = label),
    inherit.aes = FALSE,
    nudge_x = tsne_repel_data$nudge_x,
    nudge_y = tsne_repel_data$nudge_y,
    seed = 44202, max.time = 2, max.iter = 50000,
    max.overlaps = Inf, force = 12, force_pull = 0.08,
    box.padding = 0.62, point.padding = 0.17,
    min.segment.length = 0,
    size = 10.8 / ggplot2::.pt, fontface = "bold",
    label.size = 0.22, fill = scales::alpha("white", 0.90),
    color = "#202020", segment.color = "#5E6368",
    segment.size = 0.35
  ) +
  scale_color_manual(values = cluster_palette, guide = "none") +
  scale_fill_manual(values = cluster_palette, guide = "none") +
  scale_shape_manual(values = cluster_shapes, guide = "none") +
  scale_x_continuous(
    name = "t-SNE 1",
    breaks = tsne_x_breaks,
    limits = tsne_x_limits,
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    name = "t-SNE 2",
    breaks = tsne_y_breaks,
    limits = tsne_y_limits,
    expand = c(0, 0)
  ) +
  labs(
    title = "Exploratory t-SNE groups",
    subtitle = "Solid outlines contain all assigned endpoints"
  ) +
  coord_fixed(
    ratio = 1, expand = FALSE, clip = "off"
  ) +
  theme_bw(base_size = 11, base_family = "Arial") +
  theme(
    plot.title = element_text(face = "bold", size = 14.5, hjust = 0),
    plot.subtitle = element_text(
      size = 10.8, hjust = 0, color = "#555555", margin = margin(b = 4)
    ),
    axis.title = element_text(size = 14, color = "#202020"),
    axis.text = element_text(size = 11, color = "#202020"),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    panel.border = element_rect(color = "#707070", linewidth = 0.35),
    plot.margin = margin(2, 7, 5, 7)
  )

# A fixed, self-contained sidebar replaces patchwork's automatic guide
# collection. Its plot occupies exactly the same five layout columns as the
# square t-SNE plot, allowing the legend marks and text to use the full rail.
legend_title_size <- 12.6
legend_text_size <- 10.8
parameter_legend_data <- data.table(
  parameter_group = factor(group_levels, levels = group_levels),
  color = unname(group_palette[group_levels]),
  y = seq(0.895, 0.695, length.out = length(group_levels))
)
auc_legend_data <- data.table(
  signed_auc = seq(-1, 1, length.out = 201),
  y = seq(0.365, 0.555, length.out = 201)
)
auc_legend_palette <- scales::gradient_n_pal(
  colours = c("#2166AC", "#F7F7F7", "#F7F7F7", "#F7F7F7", "#B2182B"),
  values = scales::rescale(c(-1, -0.5, 0, 0.5, 1))
)
auc_legend_data[, color := auc_legend_palette(
  scales::rescale(signed_auc, to = c(0, 1))
)]
auc_legend_ticks <- data.table(
  y = seq(0.365, 0.555, length.out = 5),
  label = c("1.00", "0.75", "0.50", "0.75", "1.00")
)
cluster_legend_data <- data.table(
  cluster_id = cluster_levels,
  label = sprintf(
    "%s (n=%d)",
    sub("^vi_", "", cluster_levels),
    unname(cluster_summary_sizes[cluster_levels])
  ),
  color = unname(cluster_palette[cluster_levels]),
  shape = unname(cluster_shapes[cluster_levels]),
  y = seq(0.235, 0.035, length.out = length(cluster_levels))
)

p_sidebar_legend <- ggplot() +
  annotate(
    "text", x = 0.04, y = 0.965, label = "Parameter function",
    hjust = 0, vjust = 1, family = "Arial", fontface = "bold",
    size = legend_title_size / ggplot2::.pt, color = "#202020"
  ) +
  geom_segment(
    data = parameter_legend_data,
    aes(x = 0.05, xend = 0.24, y = y, yend = y, color = color),
    linewidth = 4.8, lineend = "butt", inherit.aes = FALSE
  ) +
  geom_text(
    data = parameter_legend_data,
    aes(x = 0.29, y = y, label = parameter_group),
    hjust = 0, vjust = 0.5, family = "Arial",
    size = legend_text_size / ggplot2::.pt, color = "#25292D"
  ) +
  annotate(
    "text", x = 0.04, y = 0.625, label = "Discriminative AUC",
    hjust = 0, vjust = 1, family = "Arial", fontface = "bold",
    size = legend_title_size / ggplot2::.pt, color = "#202020"
  ) +
  geom_rect(
    data = auc_legend_data,
    aes(
      xmin = 0.07, xmax = 0.24,
      ymin = y - 0.00052, ymax = y + 0.00052,
      fill = color
    ),
    color = NA, inherit.aes = FALSE
  ) +
  annotate(
    "rect", xmin = 0.07, xmax = 0.24, ymin = 0.365, ymax = 0.555,
    fill = NA, color = "#656A70", linewidth = 0.3
  ) +
  geom_segment(
    data = auc_legend_ticks,
    aes(x = 0.24, xend = 0.275, y = y, yend = y),
    inherit.aes = FALSE, linewidth = 0.35, color = "#555A60"
  ) +
  geom_text(
    data = auc_legend_ticks,
    aes(x = 0.30, y = y, label = label),
    hjust = 0, vjust = 0.5, family = "Arial",
    size = legend_text_size / ggplot2::.pt, color = "#25292D"
  ) +
  annotate(
    "text", x = 0.04, y = 0.305, label = "Exploratory t-SNE cluster",
    hjust = 0, vjust = 1, family = "Arial", fontface = "bold",
    size = legend_title_size / ggplot2::.pt, color = "#202020"
  ) +
  geom_point(
    data = cluster_legend_data,
    aes(x = 0.145, y = y, shape = shape, fill = color, color = color),
    inherit.aes = FALSE, size = 4.0, stroke = 0.65
  ) +
  geom_text(
    data = cluster_legend_data,
    aes(x = 0.29, y = y, label = label),
    hjust = 0, vjust = 0.5, family = "Arial",
    size = legend_text_size / ggplot2::.pt, color = "#25292D"
  ) +
  scale_color_identity() +
  scale_fill_identity() +
  scale_shape_identity() +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1), clip = "off") +
  theme_void(base_family = "Arial") +
  theme(
    plot.margin = margin(2, 7, 4, 7),
    plot.background = element_rect(fill = "white", color = NA)
  )

# The first 19 layout columns preserve exact 10:3:6 widths for the aligned
# heatmap, peak-AUC, and prior-position panels. The final five columns form a
# dedicated right sidebar: a square t-SNE panel above the stacked legends.
combined_design <- c(
  area(t = 1, l = 1,  b = 2, r = 10),
  area(t = 1, l = 11, b = 2, r = 13),
  area(t = 1, l = 14, b = 2, r = 19),
  area(t = 1, l = 20, b = 1, r = 24),
  area(t = 2, l = 20, b = 2, r = 24)
)
combined_core <- p_heat + p_peak + p_prior + p_tsne + p_sidebar_legend +
  plot_layout(
    design = combined_design,
    widths = rep(1, 24),
    heights = c(5, 9)
  )

header_plot <- ggplot() +
  annotate(
    "text", x = 0, y = 0.84,
    label = "Oxygen-dependent ploidy separation and fitted-landscape parameter structure",
    hjust = 0, vjust = 0.5, family = "Arial", fontface = "bold",
    size = 16.5 / ggplot2::.pt, color = "#202020"
  ) +
  annotate(
    "text", x = 0, y = 0.18,
    label = paste0(
      "500 separate in vivo fitted endpoints embedded with 127,500 retained initial-population rows. ",
      "All 18 displayed parameters were inputs to the in vivo-only t-SNE."
    ),
    hjust = 0, vjust = 0.5, family = "Arial",
    size = 10 / ggplot2::.pt, color = "#3D4247"
  ) +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1), clip = "off") +
  theme_void() +
  theme(plot.margin = margin(0, 12, 0, 12))

caption_plot <- ggplot() +
  annotate(
    "text", x = 0, y = 0.5,
    label = paste0(
      "Heatmap: blue associates higher values with dominant_mean_ploidy < 2; red associates higher values ",
      "with dominant_mean_ploidy \u2265 2; intensity is max(AUC, 1\u2212AUC).\n",
      "Solid full-assignment t-SNE hulls are descriptive fitted-solution summaries, ",
      "not confidence regions, independent validation, biological subtype boundaries, or causal effects."
    ),
    hjust = 0, vjust = 0.5, family = "Arial",
    size = 8.5 / ggplot2::.pt, color = "#555A60"
  ) +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1), clip = "off") +
  theme_void() +
  theme(plot.margin = margin(0, 12, 0, 12))

combined <- header_plot / combined_core / caption_plot +
  plot_layout(heights = c(0.75, 11.55, 0.45))

main_base <- file.path(figure_dir, "parameter_auc_cluster_structure")
main_output_width_in <- 20
# Match the non-label content box of the square final stacked assembly:
# 5376 px wide by 3445 px high within the 5400 x 3560 px lower-panel slot.
main_output_height_in <- 12.81622
ggsave(
  paste0(main_base, ".png"), combined,
  width = main_output_width_in, height = main_output_height_in,
  units = "in", dpi = 300, bg = "white"
)
ggsave(
  paste0(main_base, ".pdf"), combined,
  width = main_output_width_in, height = main_output_height_in,
  units = "in", device = cairo_pdf, bg = "white"
)
ggsave(
  paste0(main_base, ".svg"), combined,
  width = main_output_width_in, height = main_output_height_in, units = "in",
  device = svglite::svglite, bg = "white"
)

layout_validation <- data.frame(
  metric = c(
    "n_parameters",
    "n_fixed_o2_values",
    "n_fitted_endpoints",
    "n_initial_population_rows",
    "n_total_tsne_rows",
    "n_tsne_input_parameters",
    "n_selected_tsne_clusters",
    "selected_tsne_cluster_silhouette",
    "main_heat_peak_prior_width_ratio",
    "right_sidebar_width_fraction",
    "tsne_scatter_above_legends",
    "custom_fixed_legend_panel",
    "legend_panel_width_matches_tsne",
    "tsne_coordinate_window_square",
    "tsne_x_display_span",
    "tsne_y_display_span",
    "tsne_x_tick_breaks",
    "tsne_y_tick_breaks",
    "tsne_boundary_method",
    "tsne_region_boundaries_are_confidence_regions",
    "tsne_boundary_file",
    "tsne_points_outside_full_assignment_hulls",
    "tsne_boundary_linetype",
    "tsne_label_repel_seed",
    "tsne_repel_anchor_count",
    "parameter_axis_label_font_pt",
    "axis_title_font_pt",
    "axis_tick_font_pt",
    "function_group_annotation_full_group_height",
    "function_group_annotation_x_range",
    "function_group_annotation_to_heatmap_gap",
    "legend_title_font_pt",
    "legend_text_font_pt",
    "parameter_function_legend_items_per_row",
    "auc_colorbar_orientation",
    "cluster_legend_items_per_row",
    "all_legends_in_right_sidebar",
    "output_width_in",
    "output_height_in"
  ),
  value = c(
    uniqueN(auc$parameter),
    uniqueN(auc$O2_pct),
    nrow(clusters),
    tsne_metric("retained_initial_rows"),
    tsne_metric("total_tsne_rows"),
    tsne_metric("tsne_parameters"),
    selected_k,
    selected_silhouette,
    "10:3:6",
    "5/24",
    "TRUE",
    "TRUE",
    "TRUE",
    "TRUE",
    diff(tsne_x_limits),
    diff(tsne_y_limits),
    paste(tsne_x_breaks, collapse = ","),
    paste(tsne_y_breaks, collapse = ","),
    "all-assigned-endpoints convex hull",
    "FALSE",
    tsne_full_boundary_path,
    0,
    "solid",
    44202,
    nrow(clusters),
    15.5,
    14,
    11,
    "TRUE",
    "-0.20,-0.14",
    0.1275,
    legend_title_size,
    legend_text_size,
    1,
    "vertical",
    1,
    "TRUE",
    main_output_width_in,
    main_output_height_in
  ),
  stringsAsFactors = FALSE
)
write.table(
  layout_validation,
  file.path(data_dir, "parameter_landscape_layout_validation.tsv"),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

parameter_long[, parameter_facet := factor(
  parameter,
  levels = parameter_meta$parameter,
  labels = paste0(parameter_meta$parameter, "\ncluster input")
)]
cluster_factor_labels <- sprintf(
  "%s\n(n=%d)",
  sub("^vi_", "", cluster_levels),
  unname(cluster_summary_sizes[cluster_levels])
)
parameter_long[, cluster_id := factor(
  cluster_id,
  levels = cluster_levels,
  labels = cluster_factor_labels
)]

supp_violin <- ggplot(
  parameter_long,
  aes(x = cluster_id, y = prior_referenced_z, fill = cluster_id)
) +
  geom_hline(yintercept = 0, color = "#5F646A", linewidth = 0.35) +
  geom_violin(
    trim = TRUE, scale = "width", adjust = 0.65,
    color = "#3F4348", linewidth = 0.3, alpha = 0.88
  ) +
  geom_boxplot(
    width = 0.24, outlier.shape = NA,
    color = "#272A2E", fill = "white",
    alpha = 0.62, linewidth = 0.32
  ) +
  stat_summary(
    fun = mean, geom = "point", shape = 23, size = 2.0,
    stroke = 0.4, fill = "white", color = "#111111"
  ) +
  facet_wrap(vars(parameter_facet), ncol = 6, nrow = 3, scales = "fixed") +
  scale_fill_manual(
    values = setNames(
      unname(cluster_palette),
      cluster_factor_labels
    ),
    guide = "none"
  ) +
  scale_y_continuous(
    limits = c(-1.78, 1.78),
    breaks = c(-1.5, 0, 1.5)
  ) +
  labs(
    title = "All 18 fitted parameters across exploratory in vivo t-SNE clusters",
    subtitle = paste0(
      "Prior-referenced positions; all 18 parameters were inputs to the ",
      "in vivo-only t-SNE and best-endpoint cluster construction."
    ),
    x = "Exploratory t-SNE cluster",
    y = "Prior-referenced parameter position",
    caption = paste0(
      "Zero is the midpoint of the configured transformed interval; one unit is the SD of a uniform ",
      "distribution over that interval. Diamonds: means. These optimizer-derived endpoints are not biological replicates."
    )
  ) +
  theme_bw(base_size = 9.2, base_family = "Arial") +
  theme(
    plot.title = element_text(face = "bold", size = 14, color = "#202020"),
    plot.subtitle = element_text(size = 9, color = "#40454A", margin = margin(b = 7)),
    plot.caption = element_text(size = 7.8, color = "#555A60", hjust = 0, margin = margin(t = 7)),
    axis.title = element_text(size = 9.2),
    axis.text = element_text(size = 7.8, color = "#202020"),
    strip.text = element_text(size = 8.2, face = "bold"),
    strip.background = element_rect(fill = "#F2F3F5", color = "#BFC3C8", linewidth = 0.35),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(color = "#E3E5E8", linewidth = 0.3),
    panel.border = element_rect(color = "#70757A", linewidth = 0.35),
    plot.title.position = "plot",
    plot.margin = margin(12, 12, 12, 12)
  )

supp_base <- file.path(figure_dir, "all_parameter_prior_violins")
ggsave(
  paste0(supp_base, ".png"), supp_violin,
  width = 20, height = 10.5, units = "in", dpi = 300, bg = "white"
)
ggsave(
  paste0(supp_base, ".pdf"), supp_violin,
  width = 20, height = 10.5, units = "in", device = cairo_pdf, bg = "white"
)
ggsave(
  paste0(supp_base, ".svg"), supp_violin,
  width = 20, height = 10.5, units = "in",
  device = svglite::svglite, bg = "white"
)

source_paths <- c(
  auc_table = auc_path,
  parameter_metadata = parameter_meta_path,
  parameter_group_palette = parameter_palette_path,
  best_parameters = best_parameter_path,
  cluster_coordinates = cluster_path,
  cluster_summary = cluster_summary_path,
  tsne_run_metadata = tsne_run_metadata_path,
  parameter_bounds = bound_path,
  derived_tsne_full_assignment_boundaries = tsne_full_boundary_path,
  script = script_path
)
source_roles <- c(
  rep("input", length(source_paths) - 2L),
  "derived_output",
  "script"
)
provenance <- data.table(
  source = names(source_paths),
  role = source_roles,
  path = unname(source_paths),
  md5 = unname(tools::md5sum(source_paths))
)
fwrite(
  provenance,
  file.path(data_dir, "parameter_landscape_source_provenance.tsv"),
  sep = "\t"
)

message("Completed aligned parameter landscape and all-18 supplementary violin workflow.")
message("  Main: ", paste0(main_base, ".png"))
message("  SI: ", paste0(supp_base, ".png"))
