`.sourceCpp_1_DLLInfo` <- dyn.load('/Users/4482173/Documents/GitHub/miningcloneid/oxygen/code/O2_dynamic/.rcpp_cache_o2_invivo/shared/sourceCpp-aarch64-apple-darwin20-1.1.0/sourcecpp_542835c7dfde/sourceCpp_4.so')

cpp_o2invivo_pr_delta_vec <- Rcpp:::sourceCppFunction(function(N, p, eps_tail = 1e-8, beta_buffer = 0.0, n_exp = 1.0, smax = 1.0, N_unit = 22L) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2invivo_pr_delta_vec')
cpp_o2invivo_o2_window_supply <- Rcpp:::sourceCppFunction(function(Ntot, O2_base = 5.0, o2_min = 0.0, h_down = 1.0, K_down = 1e12, A_ang = 0.0, m_on = 9.0, m_off = 10.0, s_on = 0.3, s_off = 0.3, o2_logN_eps = 1.0) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2invivo_o2_window_supply')
cpp_o2invivo_build_B_total_triplet <- Rcpp:::sourceCppFunction(function(Nmin, Nmax, p_vec, boundary = "drop", eps_tail = 1e-8, beta_buffer = 0.0, n_exp = 1.0, smax = 1.0, N_unit = 22L) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2invivo_build_B_total_triplet')
cpp_o2invivo_build_B_WGD_triplet <- Rcpp:::sourceCppFunction(function(N0min, N0max, N1min, N1max, boundary = "drop", wgd_value = 1.0) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2invivo_build_B_WGD_triplet')
cpp_o2invivo_build_G_for_o2_triplet <- Rcpp:::sourceCppFunction(function(O2, N0min, N0max, N1min, N1max, lam_min, lam_max, k_o, has_p_misseg, p_misseg, k_o_mis, has_pmis_endpoints, pmis_O2_0, pmis_O2_1, p_const, p_wgd, boundary = "drop", eps_tail = 1e-8, beta_buffer = 0.0, n_exp = 1.0, smax = 1.0, N_unit = 22L) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2invivo_build_G_for_o2_triplet')
cpp_o2invivo_simulate_one <- Rcpp:::sourceCppFunction(function(init_state, N0min, N0max, N1min, N1max, obs_steps, sim_end_step, DT, dose, dose_ref, treat_day, fit_treatment, alpha, gamma, tx_mult_min, crowding, K, min_pop, O2_base, o2_feedback, o2_min, h_O2, K_down, A_ang, m_on, m_off, s_on, s_off, o2_logN_eps, o2_cache_bin_pct, o2_cache_hysteresis_pct, o2_cache_profile, lam_min, lam_max, k_o, has_p_misseg, p_misseg, k_o_mis, has_pmis_endpoints, pmis_O2_0, pmis_O2_1, p_const, p_wgd, boundary, eps_tail, beta_buffer, n_exp, smax, N_unit, vol_by_N, burden_floor) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2invivo_simulate_one')
cpp_o2invivo_objective_components <- Rcpp:::sourceCppFunction(function(cohort_code, dose_vec, treat_day_vec, obs_steps_list, sim_end_step_vec, obs_burden_list, keep_burden_list, ploidy_idx_list, ploidy_count_list, init_state_2N, init_state_4N, N0min, N0max, N1min, N1max, DT, dose_ref, fit_treatment, alpha, gamma, tx_mult_min, crowding, K, min_pop, O2_base, o2_feedback, o2_min, h_O2, K_down, A_ang, m_on, m_off, s_on, s_off, o2_logN_eps, o2_cache_bin_pct, o2_cache_hysteresis_pct, o2_cache_profile, lam_min, lam_max, k_o, has_p_misseg, p_misseg, k_o_mis, has_pmis_endpoints, pmis_O2_0, pmis_O2_1, p_const, p_wgd, boundary, eps_tail, beta_buffer, n_exp, smax, N_unit, vol_by_N, burden_floor, burden_log_eps, huber_k_burden_log, eps_prob, agg_burden, agg_ploidy, scenario_weight_burden, scenario_weight_ploidy, scenario_agg_huber_k) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2invivo_objective_components')

rm(`.sourceCpp_1_DLLInfo`)
