`.sourceCpp_1_DLLInfo` <- dyn.load('/Users/4482173/Documents/GitHub/miningcloneid/oxygen/code/O2_NGLF_MAP/.rcpp_cache_o2_nglf_map/shared/sourceCpp-aarch64-apple-darwin20-1.1.0/sourcecpp_17aa07f9681d1/sourceCpp_3.so')

cpp_o2simps_pr_delta_vec <- Rcpp:::sourceCppFunction(function(N, p, eps_tail = 1e-8, beta_buffer = 0.0, n_exp = 1.0, smax = 1.0, N_unit = 22L) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2simps_pr_delta_vec')
cpp_o2simps_o2_window_supply <- Rcpp:::sourceCppFunction(function(Ntot, curve_type = "gompertz", O2_cap = 5.0, o2_init = 0.5, o2_rate = 1.0, o2_shape_v = 1.0, o2_anchor_N = 1e6, o2_logN_eps = 1.0) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2simps_o2_window_supply')
cpp_o2simps_build_B_total_triplet <- Rcpp:::sourceCppFunction(function(Nmin, Nmax, p_vec, boundary = "drop", eps_tail = 1e-8, beta_buffer = 0.0, n_exp = 1.0, smax = 1.0, N_unit = 22L) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2simps_build_B_total_triplet')
cpp_o2simps_build_B_WGD_triplet <- Rcpp:::sourceCppFunction(function(N0min, N0max, N1min, N1max, boundary = "drop", wgd_value = 1.0) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2simps_build_B_WGD_triplet')
cpp_o2simps_build_G_for_o2_triplet <- Rcpp:::sourceCppFunction(function(O2, N0min, N0max, N1min, N1max, lam_min, lam_max, k_o, has_p_misseg, p_misseg, k_o_mis, has_pmis_endpoints, pmis_O2_0, pmis_O2_1, p_const, p_wgd, boundary = "drop", eps_tail = 1e-8, beta_buffer = 0.0, n_exp = 1.0, smax = 1.0, N_unit = 22L, beta_size = 0.0, alpha_o2 = 0.0, o2_ref_pct = 0.0, gamma_growth = 1.0, growth_penalty_ploidy = FALSE, growth_penalty_hypoxia = FALSE, mu_hp = 0.0) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2simps_build_G_for_o2_triplet')
cpp_o2simps_simulate_one <- Rcpp:::sourceCppFunction(function(init_state, N0min, N0max, N1min, N1max, obs_steps, sim_end_step, DT, dose, dose_ref, treat_day, fit_treatment, alpha, gamma, tx_mult_min, crowding, K, min_pop, O2_cap, o2_feedback, o2_curve_type, o2_init, o2_rate, o2_shape_v, tau_O2, o2_anchor_N, o2_logN_eps, o2_cache_bin_pct, o2_cache_hysteresis_pct, o2_cache_profile, lam_min, lam_max, k_o, has_p_misseg, p_misseg, k_o_mis, has_pmis_endpoints, pmis_O2_0, pmis_O2_1, p_const, p_wgd, boundary, eps_tail, beta_buffer, n_exp, smax, N_unit, beta_size, alpha_o2, o2_ref_pct, gamma_growth, growth_penalty_ploidy, growth_penalty_hypoxia, mu_hp, k_clear, vol_by_N, burden_floor) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2simps_simulate_one')
cpp_o2simps_objective_components_map <- Rcpp:::sourceCppFunction(function(cohort_code, dose_vec, treat_day_vec, obs_steps_list, sim_end_step_vec, obs_burden_list, keep_burden_list, ploidy_z_list, mu_by_N, sigma_burden, sigma_ploidy, init_state_2N, init_state_4N, N0min, N0max, N1min, N1max, DT, dose_ref, fit_treatment, alpha, gamma, tx_mult_min, crowding, K, min_pop, O2_cap, o2_feedback, o2_curve_type, o2_init, o2_rate, o2_shape_v, tau_O2, o2_anchor_N, o2_logN_eps, o2_cache_bin_pct, o2_cache_hysteresis_pct, o2_cache_profile, lam_min, lam_max, k_o, has_p_misseg, p_misseg, k_o_mis, has_pmis_endpoints, pmis_O2_0, pmis_O2_1, p_const, p_wgd, boundary, eps_tail, beta_buffer, n_exp, smax, N_unit, beta_size, alpha_o2, o2_ref_pct, gamma_growth, growth_penalty_mode, mu_hp, k_clear, vol_by_N, burden_floor, burden_log_eps) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_cpp_o2simps_objective_components_map')

rm(`.sourceCpp_1_DLLInfo`)
