#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OXYGEN_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
FIT_SCRIPT="${SCRIPT_DIR}/fit_invivo_model_O2_supply_demand_MAP.R"
VIZ_SCRIPT="${SCRIPT_DIR}/viz_invivo_model_O2_supply_demand_MAP_results.R"

DEFAULT_CONFIG="${OXYGEN_DIR}/config/O2_supply_demand.yaml"
CONFIG_FILE="${DEFAULT_CONFIG}"

# Runner-level settings (YAML-overridable).
RUN_PREFIX=""
OUT_ROOT=""
DATA_DIR=""
SEEDS_FILE=""
SEEDS_CSV=""
APPEND_RUN_PREFIX_TIMESTAMP="FALSE"
RUN_PREFIX_TIMESTAMP_FORMAT="%Y%m%d_%H%M%S"
AUTO_VIZ="TRUE"
VIZ_REPORT_DT="1"
VIZ_TOP_N="6"

# Fit arguments loaded from YAML (and CLI passthrough).
FIT_CFG_ARGS=()
EXTRA_ARGS=()

trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

resolve_path() {
  local p="$1"
  local base="$2"
  if [[ -z "$p" ]]; then
    printf '%s' "$p"
    return
  fi
  if [[ "$p" == /* ]]; then
    printf '%s' "$p"
    return
  fi
  if [[ "$p" == ~* ]]; then
    eval printf '%s' "$p"
    return
  fi
  printf '%s' "${base}/$p"
}

append_fit_arg() {
  local key="$1"
  local val="$2"
  FIT_CFG_ARGS+=("--${key}=${val}")
}

resolve_parameter_table_path() {
  local a
  for (( idx=${#EXTRA_ARGS[@]}-1; idx>=0; idx-- )); do
    a="${EXTRA_ARGS[$idx]}"
    if [[ "$a" == --parameter_table=* ]]; then
      printf '%s' "${a#*=}"
      return
    fi
  done
  for (( idx=${#FIT_CFG_ARGS[@]}-1; idx>=0; idx-- )); do
    a="${FIT_CFG_ARGS[$idx]}"
    if [[ "$a" == --parameter_table=* ]]; then
      printf '%s' "${a#*=}"
      return
    fi
  done
  printf '%s' ""
}

yaml_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '"%s"' "$s"
}

write_config_snapshots() {
  local run_dir="$1"
  local config_input="$2"
  local config_input_snapshot="${run_dir}/config.input.yaml"
  local config_resolved_snapshot="${run_dir}/config.resolved.yaml"
  local tmp_kv
  local tmp_resolved
  tmp_kv="$(mktemp)"
  tmp_resolved="$(mktemp)"

  cp "$config_input" "$config_input_snapshot"

  : > "$tmp_kv"
  for arg in "${FIT_CFG_ARGS[@]-}" "${EXTRA_ARGS[@]-}"; do
    case "$arg" in
      --*=*)
        local key="${arg%%=*}"
        local val="${arg#*=}"
        key="${key#--}"
        printf '%s\t%s\n' "$key" "$val" >> "$tmp_kv"
        ;;
    esac
  done

  if [[ -s "$tmp_kv" ]]; then
    awk -F '\t' '
      { idx[$1]=NR; key[NR]=$1; val[NR]=$2 }
      END {
        for (i=1; i<=NR; i++) {
          if (idx[key[i]] == i) print key[i] "\t" val[i]
        }
      }
    ' "$tmp_kv" > "$tmp_resolved"
  else
    : > "$tmp_resolved"
  fi

  {
    printf '# Resolved runtime config snapshot generated by runner\n'
    printf 'config_source: %s\n' "$(yaml_escape "$config_input")"
    printf 'run_prefix: %s\n' "$(yaml_escape "$RUN_PREFIX")"
    printf 'out_root: %s\n' "$(yaml_escape "$OUT_ROOT")"
    printf 'data_dir: %s\n' "$(yaml_escape "$DATA_DIR")"
    printf 'seeds_file: %s\n' "$(yaml_escape "${SEEDS_FILE}")"
    printf 'seeds_csv: %s\n' "$(yaml_escape "${SEEDS_CSV}")"
    printf 'seeds_use: %s\n' "$(yaml_escape "${SEEDS_USE}")"
    printf 'seed_source: %s\n' "$(yaml_escape "${SEED_SOURCE}")"
    printf 'append_run_prefix_timestamp: %s\n' "$(yaml_escape "${APPEND_RUN_PREFIX_TIMESTAMP}")"
    printf 'run_prefix_timestamp_format: %s\n' "$(yaml_escape "${RUN_PREFIX_TIMESTAMP_FORMAT}")"
    printf 'auto_viz: %s\n' "$(yaml_escape "${AUTO_VIZ}")"
    printf 'viz_report_dt: %s\n' "$(yaml_escape "${VIZ_REPORT_DT}")"
    printf 'viz_top_n: %s\n' "$(yaml_escape "${VIZ_TOP_N}")"
    printf 'run_dir: %s\n' "$(yaml_escape "${run_dir}")"
    printf 'fit_script: %s\n' "$(yaml_escape "${FIT_SCRIPT}")"
    printf 'viz_script: %s\n' "$(yaml_escape "${VIZ_SCRIPT}")"
    printf 'fit_args:\n'
    while IFS=$'\t' read -r k v || [[ -n "${k:-}" ]]; do
      [[ -z "${k:-}" ]] && continue
      printf '  %s: %s\n' "$k" "$(yaml_escape "$v")"
    done < "$tmp_resolved"
  } > "$config_resolved_snapshot"

  rm -f "$tmp_kv" "$tmp_resolved"
  printf '%s\t%s\n' "$config_input_snapshot" "$config_resolved_snapshot"
}

load_config() {
  local cfg_path="$1"
  local cfg_dir="$2"
  [[ -f "$cfg_path" ]] || { echo "ERROR: config not found: $cfg_path" >&2; exit 1; }

  while IFS= read -r raw || [[ -n "$raw" ]]; do
    local line="${raw%%#*}"
    line="$(trim "$line")"
    [[ -z "$line" ]] && continue
    [[ "$line" != *:* ]] && continue

    local key="${line%%:*}"
    local val="${line#*:}"
    key="$(trim "$key")"
    val="$(trim "$val")"

    if [[ "$val" == "\""*"\"" && "$val" == *"\"" ]]; then
      val="${val:1:${#val}-2}"
    elif [[ "$val" == "'"*"'" && "$val" == *"'" ]]; then
      val="${val:1:${#val}-2}"
    fi

    case "$key" in
      run_prefix) RUN_PREFIX="$val" ;;
      out_root) OUT_ROOT="$(resolve_path "$val" "$cfg_dir")" ;;
      data_dir) DATA_DIR="$(resolve_path "$val" "$cfg_dir")" ;;
      seeds_file) SEEDS_FILE="$(resolve_path "$val" "$cfg_dir")" ;;
      seeds_csv) SEEDS_CSV="$val" ;;
      append_run_prefix_timestamp) APPEND_RUN_PREFIX_TIMESTAMP="$val" ;;
      run_prefix_timestamp_format) RUN_PREFIX_TIMESTAMP_FORMAT="$val" ;;
      auto_viz) AUTO_VIZ="$val" ;;
      viz_report_dt) VIZ_REPORT_DT="$val" ;;
      viz_top_n) VIZ_TOP_N="$val" ;;
      parameter_table)
        append_fit_arg "$key" "$(resolve_path "$val" "$cfg_dir")"
        ;;
      *)
        append_fit_arg "$key" "$val"
        ;;
    esac
  done < "$cfg_path"
}

for arg in "$@"; do
  case "$arg" in
    --config=*) CONFIG_FILE="${arg#*=}" ;;
  esac
done

if [[ "$CONFIG_FILE" != /* ]]; then
  CONFIG_FILE="$(resolve_path "$CONFIG_FILE" "$PWD")"
fi
CONFIG_DIR="$(cd "$(dirname "$CONFIG_FILE")" && pwd)"
load_config "$CONFIG_FILE" "$CONFIG_DIR"

for arg in "$@"; do
  case "$arg" in
    --config=*) ;;
    --run_prefix=*) RUN_PREFIX="${arg#*=}" ;;
    --out_root=*) OUT_ROOT="$(resolve_path "${arg#*=}" "$PWD")" ;;
    --data_dir=*) DATA_DIR="$(resolve_path "${arg#*=}" "$PWD")" ;;
    --seeds_file=*) SEEDS_FILE="$(resolve_path "${arg#*=}" "$PWD")" ;;
    --seeds_csv=*) SEEDS_CSV="${arg#*=}" ;;
    --append_run_prefix_timestamp=*) APPEND_RUN_PREFIX_TIMESTAMP="${arg#*=}" ;;
    --run_prefix_timestamp_format=*) RUN_PREFIX_TIMESTAMP_FORMAT="${arg#*=}" ;;
    --auto_viz=*) AUTO_VIZ="${arg#*=}" ;;
    --viz_report_dt=*) VIZ_REPORT_DT="${arg#*=}" ;;
    --viz_top_n=*) VIZ_TOP_N="${arg#*=}" ;;
    --parameter_table=*)
      EXTRA_ARGS+=("--parameter_table=$(resolve_path "${arg#*=}" "$PWD")")
      ;;
    --*=*)
      EXTRA_ARGS+=("$arg")
      ;;
    *)
      EXTRA_ARGS+=("$arg")
      ;;
  esac
done

require_nonempty() {
  local name="$1"
  local value="$2"
  if [[ -z "${value}" ]]; then
    echo "ERROR: required value '${name}' is empty. Set it in YAML or CLI." >&2
    exit 1
  fi
}

require_nonempty "run_prefix" "${RUN_PREFIX}"
require_nonempty "out_root" "${OUT_ROOT}"
require_nonempty "data_dir" "${DATA_DIR}"
if [[ -z "${SEEDS_FILE}" && -z "${SEEDS_CSV}" ]]; then
  echo "ERROR: set seeds_file or seeds_csv in YAML/CLI." >&2
  exit 1
fi

if [[ "${APPEND_RUN_PREFIX_TIMESTAMP}" == "TRUE" || "${APPEND_RUN_PREFIX_TIMESTAMP}" == "true" || "${APPEND_RUN_PREFIX_TIMESTAMP}" == "1" ]]; then
  ts_suffix="$(date +"${RUN_PREFIX_TIMESTAMP_FORMAT}")"
  RUN_PREFIX="${RUN_PREFIX}_${ts_suffix}"
fi

read_seeds_from_file() {
  local f="$1"
  Rscript --vanilla - "$f" <<'RS'
args <- commandArgs(trailingOnly = TRUE)
f <- args[[1]]
if (!file.exists(f)) { cat(""); quit(save = "no", status = 0) }
ln <- readLines(f, warn = FALSE)
ln <- gsub("\\r", "", ln)
ln <- ln[nzchar(trimws(ln))]
if (length(ln) == 0L) { cat(""); quit(save = "no", status = 0) }
raw <- paste(ln, collapse = ",")
parts <- trimws(unlist(strsplit(raw, "[,]", fixed = FALSE)))
parts <- parts[nzchar(parts)]
parts <- parts[!tolower(parts) %in% c("seed", "seeds")]
nums <- suppressWarnings(as.integer(parts))
nums <- nums[is.finite(nums)]
if (length(nums) == 0L) { cat(""); quit(save = "no", status = 0) }
cat(paste(nums, collapse = ","))
RS
}

SEEDS_FROM_FILE=""
if [[ -n "${SEEDS_FILE}" ]]; then
  SEEDS_FROM_FILE="$(read_seeds_from_file "${SEEDS_FILE}")"
fi
if [[ -n "${SEEDS_FROM_FILE}" ]]; then
  SEEDS_USE="${SEEDS_FROM_FILE}"
  SEED_SOURCE="file:${SEEDS_FILE}"
else
  SEEDS_USE="${SEEDS_CSV}"
  SEED_SOURCE="arg:--seeds_csv"
fi
if [[ -z "${SEEDS_USE}" ]]; then
  echo "ERROR: no seeds found. Provide ${SEEDS_FILE} or --seeds_csv." >&2
  exit 1
fi

mkdir -p "${OUT_ROOT}"
RUN_DIR="${OUT_ROOT}/${RUN_PREFIX}"
mkdir -p "${RUN_DIR}"
RUN_LOG="${RUN_DIR}/run_status.log"
SNAPSHOT_PATHS="$(write_config_snapshots "${RUN_DIR}" "${CONFIG_FILE}")"
CONFIG_INPUT_SNAPSHOT="${SNAPSHOT_PATHS%%$'\t'*}"
CONFIG_RESOLVED_SNAPSHOT="${SNAPSHOT_PATHS#*$'\t'}"
PARAM_TABLE_PATH="$(resolve_parameter_table_path)"
if [[ -n "${PARAM_TABLE_PATH}" && -f "${PARAM_TABLE_PATH}" ]]; then
  cp -f "${PARAM_TABLE_PATH}" "${RUN_DIR}/parameter_table.csv"
fi
touch "${RUN_LOG}"
exec > >(tee -a "${RUN_LOG}") 2>&1

echo "Running O2_supply_demand_MAP"
echo "  Config: ${CONFIG_FILE}"
echo "  Config input snapshot: ${CONFIG_INPUT_SNAPSHOT}"
echo "  Config resolved snapshot: ${CONFIG_RESOLVED_SNAPSHOT}"
echo "  Fit script: ${FIT_SCRIPT}"
echo "  Data dir: ${DATA_DIR}"
echo "  Seeds: ${SEEDS_USE} (${SEED_SOURCE})"
echo "  Run dir: ${RUN_DIR}"
echo "  Run log: ${RUN_LOG}"
if [[ -n "${PARAM_TABLE_PATH}" && -f "${PARAM_TABLE_PATH}" ]]; then
  echo "  Parameter table snapshot: ${RUN_DIR}/parameter_table.csv"
else
  echo "  Parameter table snapshot: (missing --parameter_table or file not found)"
fi
echo "  Run prefix timestamp suffix: ${APPEND_RUN_PREFIX_TIMESTAMP} (format=${RUN_PREFIX_TIMESTAMP_FORMAT})"
echo "  Auto viz: ${AUTO_VIZ} (report_dt=${VIZ_REPORT_DT}, top_n=${VIZ_TOP_N})"

IFS=',' read -r -a seed_arr <<< "${SEEDS_USE}"
for seed in "${seed_arr[@]}"; do
  seed="$(echo "$seed" | tr -d '[:space:]')"
  [[ -z "$seed" ]] && continue
  run_dir="${RUN_DIR}/seed${seed}"
  mkdir -p "${run_dir}"
  if [[ -n "${PARAM_TABLE_PATH}" && -f "${PARAM_TABLE_PATH}" ]]; then
    cp -f "${PARAM_TABLE_PATH}" "${run_dir}/parameter_table.csv"
  fi
  fit_log="${run_dir}/fit_status.log"
  viz_log="${run_dir}/viz_status.log"
  cmd=(
    Rscript "${FIT_SCRIPT}"
    "--seed=${seed}"
    "--out_dir=${run_dir}"
    "--data_dir=${DATA_DIR}"
  )
  if [[ ${#FIT_CFG_ARGS[@]} -gt 0 ]]; then
    cmd+=("${FIT_CFG_ARGS[@]}")
  fi
  if [[ ${#EXTRA_ARGS[@]} -gt 0 ]]; then
    cmd+=("${EXTRA_ARGS[@]}")
  fi
  echo "[$(date '+%F %T')] seed=${seed}: start"
  echo "[$(date '+%F %T')] seed=${seed}: fit_log=${fit_log}"
  echo "Command: ${cmd[*]}"
  "${cmd[@]}" 2>&1 | tee "${fit_log}"
  echo "[$(date '+%F %T')] seed=${seed}: done"

  if [[ "${AUTO_VIZ}" == "TRUE" || "${AUTO_VIZ}" == "true" || "${AUTO_VIZ}" == "1" ]]; then
    viz_cmd=(
      Rscript "${VIZ_SCRIPT}"
      "--fit_dir=${run_dir}"
      "--data_dir=${DATA_DIR}"
      "--report_dt=${VIZ_REPORT_DT}"
      "--top_n=${VIZ_TOP_N}"
      "--n_cores=1"
    )
    echo "[$(date '+%F %T')] seed=${seed}: viz start"
    echo "[$(date '+%F %T')] seed=${seed}: viz_log=${viz_log}"
    echo "Viz command: ${viz_cmd[*]}"
    "${viz_cmd[@]}" 2>&1 | tee "${viz_log}"
    echo "[$(date '+%F %T')] seed=${seed}: viz done"
  fi
done

echo "All done. Run directory: ${RUN_DIR}"
